### ISSUE TITLE
The option to split Yaml & content

### ISSUE THREAD

**Issue by katoquro** [sysgears/grain#15]
Hello, 

I have a little but very annoying usability issue. Now content file represents two types: yaml & layout (md, html...). It's quite convenient but my IDE (Intellij IDEA) goes crazy. Code formatting feature cannot work properly and I have to select layout code every time before formatting to prevent yaml part  "deindentation".
Can these types of content file be split? For example to optional *.yml file.

Thanks

**Comment by vlasenko** [comment]
Hi,

Sounds like it is not the issue with Grain, but rather with IDE, but it is possible to achieve solution with Grain. 

You can put headers and content separately. For example:
page_c.md <-- content goes here
page.md <-- header goes here

Then you exclude all _c files from Grain engine processing, e.g. in SiteConfig.groovy add
excludes << /[^_]*_c\.(md|html|adoc)/

The relevant documentation section:
http://sysgears.com/grain/docs/latest/#source-processing-configuration

After that in Resource Mapper you add back content part to header-only resources:

resources.collect { Map resource ->
    def contentFile = new File(...) // Build correct _c file path from resource location here
    resource.source = contentFile.text // Set contents of the resource
}

The relevant documentation section:
http://sysgears.com/grain/docs/latest/#resource-representation

**Comment by katoquro** [comment]
Ok, I'll try with my case
page.md <- content 
page.yml <- variables

I thought that this feature can be included into core because it is might be difficult to upgrade grain with contains a lot of custom code.

**Comment by vlasenko** [comment]
This is possible as well in this case

You exclude all html/md files from Grain engine processing, e.g. in SiteConfig.groovy add
excludes << /.*\.(md|html|adoc)/

After that in Resource Mapper you add back content part to header-only resources AND you need to set the markup type:

``` groovy
resources.collect { Map resource ->
    def contentFile = new File(...) // Build correct file path from resource location here
    resource.source = contentFile.text // Set contents of the resource
    resource.markup = 'html' // Set markup type, e.g. html, md or adoc
}
```
